# Generated by Django 4.0.7 on 2022-09-28 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobfindr.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('custom_field', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('course', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=jobfindr.models.Profile.user_directory_path)),
                ('fullname', models.CharField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('about', models.TextField(blank=True, max_length=1024, null=True)),
                ('certificates', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('contact_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='jobfindr.contact')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='jobfindr.education')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='jobfindr.experience')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(related_name='user_profile', to='jobfindr.skill')),
            ],
        ),
    ]
