# Generated by Django 4.0.7 on 2022-09-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0002_contact_education_experience_skill_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
