# Generated by Django 4.0.7 on 2022-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0006_remove_profile_education_remove_profile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
