# Generated by Django 4.0.7 on 2022-09-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0008_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
