# Generated by Django 4.0.7 on 2022-09-30 21:55

from django.db import migrations, models
import django.db.models.deletion
import jobfindr.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0009_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='jobfindr.contact'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=jobfindr.models.Profile.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='jobfindr.skill'),
        ),
    ]
