# Generated by Django 4.0.7 on 2022-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfindr', '0010_alter_profile_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='custom_field',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
