version: '3.8'

services:
  mariadatabase:
    image: mariadb
    container_name: mariadatabase
    volumes:
      - capstone_db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: capstone_db

  api:
    container_name: api
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      mariadatabase:
        condition: service_healthy
    restart: on-failure
    environment:
      IS_CONTAINER: 1
      IS_CICD_TESTING: '${IS_CICD_TESTING}'
      SECRET_KEY: "${SECRET_KEY}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_TEST_USER: "${DB_TEST_USER}"
      DB_TEST_PASS: "${DB_TEST_PASS}"

  front:
    container_name: front
    build: ./jobfindr_frontend
    volumes:
      - ./jobfindr_frontend:/usr/src/app_front
    ports: 
      - "3000:3000"
    depends_on:
      - api
    command: npm run dev

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  test:
    container_name: test
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "6666:6666"
    depends_on:
      - front
    environment:
      IS_CONTAINER: 1
      IS_CICD_TESTING: 1
      SECRET_KEY: "${SECRET_KEY}"
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_TEST_USER: "${DB_TEST_USER}"
      DB_TEST_PASS: "${DB_TEST_PASS}"

    command: python manage.py test --keepdb

volumes:
  capstone_db_data: