version: '3.7'

services:
  mariadatabase:
    image: mariadb
    volumes:
      - capstone_db_data:/var/lib/mysql
    ports:
      - "3307:3307"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: capstone_db

  api:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mariadatabase
    environment:
      - IS_CONTAINER=1

  front:
    build: ./jobfindr_frontend
    volumes:
      - ./jobfindr_frontend:/usr/src/app_front
    ports: 
      - "3000:3000"
    depends_on:
      - api
    command: npm run dev

volumes:
  capstone_db_data: