version: '3.7'

services:
  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  db:
    image: mariadb
    volumes:
      - capstone_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: capstone_db

  api:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      IS_CONTAINER: 1
      SECRET_KEY: "${SECRET_KEY}"
    
  front:
    build: ./jobfindr_frontend
    volumes:
      - ./jobfindr_frontend:/usr/src/app_front
    ports: 
      - "3000:3000"
    depends_on:
      - api
    command: npm run dev

  test:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "6666:6666"
    depends_on:
      - front
      - selenium
      - db
    environment:
      - IS_CONTAINER=1
      - IS_CICD_TESTING=1
    command: python manage.py test --keepdb

volumes:
  capstone_db_data: