version: '3.7'

services:
  db:
    image: mariadb
    volumes:
      - capstone_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: capstone_db

  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db


volumes:
  capstone_db_data: