name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: db
      image: mariadb:10.3 
      env:    
          MARIADB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASS }}
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}          

      ports:  
      - 3306:3306 
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_HOST: ${{ secrets.DB_HOST }}
      run: |
        python manage.py test
