name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASS }}
          MARIADB_USER: ${{ secrets.DB_USER }}
          MARIADB_PASSWORD: ${{ secrets.DB_PASS }}
        ports: ['3306:3306']
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
        DB_TEST_PASS: ${{ secrets.DB_TEST_PASS }}
        DB_HOST: 127.0.0.1
        IS_CONTAINER: 1
        IS_CICD_TESTING: 1
      run: |
        python manage.py test
